//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.Room_reservation = new HashSet<Room_reservation>();
        }

        public int client_id { get; set; }

        [Display(Name = "First Name")]
        [StringLength(50, ErrorMessage = "Input client first name!", MinimumLength = 1)]
        public string client_first_name { get; set; }

        [Display(Name = "Last Name")]
        [StringLength(100, ErrorMessage = "Input client last name!", MinimumLength = 1)]
        public string client_last_name { get; set; }

        [Display(Name = "Age")]
        public int client_age { get; set; }

        [Display(Name = "Phone number")]
        public int client_phone_number { get; set; }

        [Display(Name = "Address")]
        [StringLength(250)]
        public string client_address { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room_reservation> Room_reservation { get; set; }
    }
}
