//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employees
    {
        public int employee_id { get; set; }

        [Display(Name = "First Name")]
        [StringLength(50, ErrorMessage = "Input employee first name!", MinimumLength = 1)]
        public string employee_first_name { get; set; }

        [Display(Name = "Last Name")]
        [StringLength(50, ErrorMessage = "Input employee last name!", MinimumLength = 1)]
        public string employee_last_name { get; set; }

        [Display(Name = "Salary")]
        public decimal employee_salary { get; set; }

        [Display(Name = "Position")]
        public string employee_position { get; set; }
    }
}
