//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Room_reservation
    {
        public int room_reservation_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> room_id { get; set; }

        [Display(Name = "Room Price")]
        public decimal price { get; set; }

        [Display(Name = "Check in date")]
        [DataType(DataType.Date)]
        public System.DateTime check_in { get; set; }

        [Display(Name = "Check out date")]
        [DataType(DataType.Date)]
        public System.DateTime check_out { get; set; }

        public virtual Clients Clients { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
